development:
    adapter: mysql2
    database: eskolarship
    username: root
    password: password

test:
    adapter: mysql2
    database: eskolarship
    username: root
    password: password

production:
    adapter: mysql2
    database: eskolarship
    username: root
    password: password